[package]
name = "gyros"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.23"
